name: Kodi Addon-Check

on: [push]

jobs:
  kodi-addon-checker:
    name: Kodi addon checker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Clean workspace
      run: |
        rm -r tools

    - name: Kodi addon checker validation
      id: kodi-addon-checker
      uses: xbmc/action-kodi-addon-checker@v1.0
      with:
        kodi-version: matrix
